### ISSUE TITLE
[BUG] 스플릿 뷰 이용시 네비게이션 바 아이템들 사라지는 버그

### ISSUE THREAD

**Issue by Lim-YongKwan** [DeveloperAcademy-YOLO/ProjectYOLO#117]
# Bug note
> Step-by-step explanation of what situation occurred from the start to the bug

1. 네비게이션 바 아이템이 중간에 있는 화면으로 실행
2. 스플릿 뷰 실행
3. 다시 최대화 실행 
4. 버그 발견

## Screenshot

- screenshot

https://user-images.githubusercontent.com/96565110/196962730-1faa3c8a-26aa-4cda-a192-4e9e188d9a23.mp4

https://user-images.githubusercontent.com/96565110/196962849-f57511e9-280d-4b8e-af6f-f5cd2ea8a45a.mp4

## Expected result
> Write down the specific results that need to be corrected.

- 유저가 앱의 퀄리티를 의심할 수 있다.

## References
> In the case of the view shown, a screenshot is also attached.

- write here

**Comment by kelly-chui** [comment]
해결됨
