### ISSUE TITLE
[BUG]앱 전반적인 테스트 (유저가 페이퍼를 생성하고 확인하는 스토리에 대해서)__ 221027 업뎃

### ISSUE THREAD

**Issue by dgfghsjd** [DeveloperAcademy-YOLO/ProjectYOLO#120]
# Bug note

해결 완료한 것은 체크표시 해주시기 바랍니다~!
# 221021 
- [x] 설정버튼 통해서 로그인 하면 아이디, 비번 입력창에서 내 정보 화면으로 안 바뀌고 사이드 바의 이름만 게스트에서 닉네임으로 변경됨.
- [x]  페이퍼 생성하기 버튼을 눌러도 실제로 생성이 안 됨.(papersubject에 추가가 안 됨)
- [x]  페이퍼 생성하기 버튼 눌렀을 떄 제목이 바로 반영이 안됨
- [x] 보관함의 페이퍼들을 클릭하면 클릭한 페이퍼의 메모리가 남음. 예를들어 1번 페이퍼 누르면 제목이 잘 뜨는데, 2번 페이퍼 누르면 1번 페이퍼의 제목이 뜨고 3번 페이퍼를 누르면 2번 페이퍼의 제목이 뜸
- [x] 페이퍼 변경, 수정, 삭제로직에 전달인자로 페이퍼가 아닌 페이퍼의 ID를 줘야 할 것 같습니다. -> 페이퍼를 주는 방식으로 해결됨
- [ ] 페이퍼 마감하기 기능이 없음 -> 2차 스프린트에서 해결할 예정
- [x] 앱을 껐다 키면 로컬에 저장되어있던 페이어 다 날아감

# 221025
 - [x] 페이퍼 보관함에 1개의 페이퍼만 있을 때 그 페이퍼를 지우면 앱이 꺼짐
 - [x] 페이퍼의 마감시간이 한 박자 늦게 적용 됨
 - [x] 앱이 처음 켜졌을 떄 메인 뷰인 "페이퍼 템플릿"에 파란 배경이 깔리지 않음
 - [x] 페이퍼 화면에서 뒤로가기 버튼을 더블클릭해야 뒤로 가짐

# 221026
 - [x] 앱을 처음 켜면 게스트인 상태로 자동으로 로그인이 되어있음, 근데 페이퍼에서 링크버튼을 누르면 로그인 화면이 떠서 페이퍼는 '게스트'인 상태로 로그인 했다는 걸 인식 못 함
 - [x] 게스트 로그인 상태에서 회원탈퇴가 안 눌림
 - [x] 앱 처음 화면에서 사이드바에 요셉이라 써있음, 아무 기능이 없는데 셰브론이 있어 버튼같음
 - [x] 회원 탈퇴가 소리소문 없이 됨
 - [x] 회원가입 화면에서 로그인 버튼을 누르면 로그인 화면으로 넘어가고, 다시 회원가입 버튼을 누르면 원래 입력했던 정보가 날아감, 회원가입 화면에 로그인 버튼이 있는 것이 어색합니다.
 - [x] 회원가입을 완료하면 로그인 화면으로 넘어가는데 아무것도 안 해도 갑자기 아이디, 비번을 입력하는 텍스트필드가 빨간표시가 되며 비번 입력창 아래에 오류 메세지가 뜸
 - [x] 회원가입을 완료 해도 로그인 창에서 썼던 정보들이 남아있음
 - [x] 링크 공유를 하면 특정 페이퍼의 화면이 아닌 보관함으로 감 

# 221027
 - [x] 로그인 후 템플릿을 선택하고 설정에 들어가 로그아웃 한 후에 템플릿 화면을 가면 템플릿 선택창이 아닌 로그아웃 전에 골랐던 템플릿의 화면이 나옴
 - [x] #197

## Screenshot

- screenshot

## Expected result
> Write down the specific results that need to be corrected.

- write here

## References
> In the case of the view shown, a screenshot is also attached.

- write here

**Comment by Kelly-Chui** [comment]
여러 버그를 하나의 이슈로 묶는 것이 아닌 각각의 이슈로 분리시키는게 나을 것 같습니다.

**Comment by dgfghsjd** [comment]
아 이건 이 이슈대로 브랜치 만들 것은 아니고 유저플로우 하나 정해서 그 과정에서 일어나는 오류들 기록용입니다
