### ISSUE TITLE
[Feature] Feat Deep Link

### ISSUE THREAD

**Issue by Lim-YongKwan** [DeveloperAcademy-YOLO/ProjectYOLO#125]
# Please write a story
- Please write tasks
   - 딥 링크 기능 구현

## 🤔 Completion Conditions

- [ ] URL을 통해서 해당 앱을 다운받고 원하는 페이지에 갈 수가 있어야 한다.
- [ ] 추후 푸시 노티피케이션 쪽에서도 원하는 페이지에 갈 수가 있어야 한다.

## 🎨 Design Screenshot (Optional)

- Screenshot

**Comment by kelly-chui** [comment]
해결됨
