### ISSUE TITLE
[Fix] 버그 테스트__20221123 update

### ISSUE THREAD

**Issue by dgfghsjd** [DeveloperAcademy-YOLO/ProjectYOLO#313]
# Bug note
- [x] 로그인을 했을 때 프로필 사진 변경에 대한 사진 접근 권한을 너무 일찍 띄웁니다.
- [x] 설정화면에서 닉네임만 바꾸고 편집 완료 했을 때 사진 위에 스피너가 계속 돌고 안 사라집니다. 
- [x] 페이퍼 화면에서 카드를 생성 후 보관함으로 가지 않고 페이퍼 화면에서 앱을 끄고 다시 켜면 만들었던 카드들이 NSCacheManager에 저장이 안되서 사라집니다.
- [x] 보관함에서 특정 페이퍼로 넘어갈 때 로딩페이지가 있어야 합니다. 가끔가다 페이퍼의 정보를 제대로 못 읽어옵니다.
   - 현재 페이퍼에 대한 바인딩이 제대로 안 되어있어 생기는 문제입니다.
   - #331  이슈로 해결할 예정입니다.
- [x] 어떤 사람(A)이 게스트 일 때 만든 페이퍼들이 다른 사람(B)이 로그인을 하면 모두 로그인 한 유저(B)가 만든 것으로 됩니다. 
   - 페이퍼 안에서 로그인 하는 것과 설정 창에서 로그인 해주는 것을 구분 해줄 수 있는가?
   - Wri~뷰컨 175 번째 줄. 어디서 로그인 했는지 
   - [7e020e0] 커밋으로 해결했습니다
- [x] 마감을 누르지 않고 자연적으로 시간이 다 된 페이퍼들이 보관함에서 '종료된 페이퍼'로 이동하지만 + 버튼이 살아있습니다.
     - #349  이슈로 해결했습니다.
- [x] 페이퍼 모델 강제 타입 지정 풀기
     - #349  이슈로 해결했습니다.
- [x] 회원탈퇴를 하면 자동으로 로그아웃 되지 않고 유저가 직접 로그아웃 해줘야 합니다(@PJunyeong)
   - 그래서 회원탈퇴를 무한으로 할 수 있습니다
   - 탈퇴했을 때 계정을 지워주는 것은 제대로 작동합니다. → 아래 문제로 해결 가능
   - [x] 회원 가입, 로그인, 로그아웃, 회원탈퇴 등 현재 유저 상황에 따라 설정 / 프로필 뷰 인터렉션
   - #338  pr 로 해결 

## Screenshot

- screenshot

## Expected result
> Write down the specific results that need to be corrected.

- write here

## References
> In the case of the view shown, a screenshot is also attached.

- write here

**Comment by PJunyeong** [comment]
페이퍼 화면에서 카드를 생성 후 보관함으로 가지 않고 페이퍼 화면에서 앱을 끄고 다시 켜면 만들었던 카드들이 NSCacheManager에 저장이 안되서 사라집니다. → 저희 (실제) 페이퍼 저장이 카드를 추가할 때마다 이루어지는 건가요??

**Comment by dgfghsjd** [comment]
지금은 페이퍼에 카드들을 추가하고 뒤로가기 해야만 저장이 되는데 보통은 카드를 추가하고 앱을 나갔을 때 작성한 카드가 저장이 될거라 생각하기 때문에 카드들을 추가할 때마다 카드들도 캐시에 저장되도록 해줘야 할 것 같습니다.
