### ISSUE TITLE
[Fix] Context Menu 눌렀을 때 깜빡이는 현상

### ISSUE THREAD

**Issue by ddophi98** [DeveloperAcademy-YOLO/ProjectYOLO#328]
# Bug note
- [X] Context Menu 눌렀을 때 1초마다 컬렉션 뷰의 셀들이 깜빡임 
- [ ] Context Menu 눌렀다 땠을 때 셀들이 잠깐 깜빡일 때가 있음

**Comment by Lim-YongKwan** [comment]
실기기에서만 일어나는 문제 같은데 도대체 왜 이럴까요ㅠㅠ
