### ISSUE TITLE
[Fix] 딥링크 페이퍼 카드 추가하기 문제

### ISSUE THREAD

**Issue by Lim-YongKwan** [DeveloperAcademy-YOLO/ProjectYOLO#329]
# Bug note
> Step-by-step explanation of what situation occurred from the start to the bug

1. Go to '카카오톡'
2. Click on '공유하기'
3. Action to '페이퍼 추가하기'
5.  공유받은 페이퍼에 대해 만약 게스트라면 그 페이퍼에 카드 추가를 하면 안된다. 
       - 이슈 안에서 해결할 예정입니다.

## Screenshot

- screenshot

https://user-images.githubusercontent.com/96565110/202940200-06613d86-650b-4a9a-8eb2-c6cdf51c16b1.MP4

## Expected result
> 심각한 UX 문제.

**Comment by dgfghsjd** [comment]
5번 추가, 게스트에 대한 UX 수정. 

게스트는 앱을 설치한 후 페이퍼 생성과 그 페이퍼의 카드 추가는 자유롭게 할 수 있으나 

공유 받은 페이퍼에 대한 수정은 부가적인 기능이므로 로그인을 해야만 할 수 있다.

**Comment by dgfghsjd** [comment]
업데이트 하고 출시한 후에야 테스트를 해볼 수 있다고 합니다.

**Comment by dgfghsjd** [comment]
버그의 현상: 공유 받은 페이퍼는 VM의 isLocalDB의 값이 false이고, 카드 추가가 되지 않는다.

**Comment by dgfghsjd** [comment]
추가) 페이퍼 화면 처음에 로드될 때 탭 제스처 지우기 -> 완료

**Comment by dgfghsjd** [comment]
추가) 로그인한 상태에서 페이퍼 생성한 후 마감하기 누르면 UI가 바뀌나 곧 마감을 누르기 전 UI 도 되돌아옴 -> 완료
