### ISSUE TITLE
[Feature] PaperStorage

### ISSUE THREAD

**Issue by ddophi98** [DeveloperAcademy-YOLO/ProjectYOLO#55]
# Please write a story
- Please write tasks
   - 진행중 / 종료된 페이퍼들을 볼 수 있는 보관함입니다.

## 🤔 Completion Conditions
- [x] 컬렉션뷰를 만들고 두개의 섹션에 각각 진행중인 페이퍼와 종료된 페이퍼를 넣는다
- [ ] 작은 미리보기 구현하기
- [x] 타이머 구현하기
- [x] 컬렉션 뷰 셀 구현하기
- [x] 사이드바에서 해당뷰로 이어지게 연결하기
- [ ] 페이퍼를 터치하면 해당 페이퍼로 이동하기

## 🎨 Design Screenshot (Optional)
<img width="881" alt="image" src="https://user-images.githubusercontent.com/72330884/195230812-4c45022c-2fec-4e92-b052-129caf463ace.png">

**Comment by Kelly-Chui** [comment]
넘 빨라 넘 잘해
