### ISSUE TITLE
[Design] Sidebar Layout

### ISSUE THREAD

**Issue by Kelly-Chui** [DeveloperAcademy-YOLO/ProjectYOLO#73]
# Please write a story
- Please write tasks
    - Sidebar에 표시되는 Userinfo의 레이아웃을 조정합니다.

## 🎨 Design Screenshot

- Screentshot
- ![](https://i.imgur.com/i7skRkn.png)

## 🤔 completion Conditions

- [x] UserName, UserPhoto Stack으로 감싸기
- [ ] Hi-Fi 디자인에 맞게 레이아웃 조정하기
- [x] NSLayout을 SnapKit으로 바꾸기

**Comment by Kelly-Chui** [comment]
현재 상황
<img width="1369" alt="Screen Shot 2022-10-15 at 4 28 44 AM" src="https://user-images.githubusercontent.com/57012734/195928185-2a1c492e-3755-4953-b8a8-bbd96f127b20.png">

UserinfoStack의 사이즈를 반응형으로 만들거나 SidebarViewd의 크기를 조정할 필요가 있습니다.

**Comment by teethemoji** [comment]
그러면 이런 식으로 SidebarView의 trailingAnchor를 기준으로 constant값을 지정해주면 될까요?
<img width="651" alt="image" src="https://user-images.githubusercontent.com/60784937/196019390-49387f76-1ca6-478a-bf59-dcd94ca886a8.png">

**Comment by Kelly-Chui** [comment]
> 그러면 이런 식으로 SidebarView의 trailingAnchor를 기준으로 constant값을 지정해주면 될까요?
> <img alt="image" width="651" src="https://user-images.githubusercontent.com/60784937/196019390-49387f76-1ca6-478a-bf59-dcd94ca886a8.png">

Good 좋아보입니다!

<img width="1369" alt="Screen Shot 2022-10-16 at 5 33 06 PM" src="https://user-images.githubusercontent.com/57012734/196026192-0a61b7be-7042-489d-8b11-5c3e27c10e90.png">
<img width="1370" alt="Screen Shot 2022-10-16 at 5 33 44 PM" src="https://user-images.githubusercontent.com/57012734/196026216-18b8373d-c254-4bd2-a2d9-73b4ce399f48.png">
