### ISSUE TITLE
[Feature] 서버 페이퍼 만료 시 구현 양식 논의

### ISSUE THREAD

**Issue by PJunyeong** [DeveloperAcademy-YOLO/ProjectYOLO#78]
* 브랜치 용 이슈가 아니라 논의가 필요한 이슈입니다

파이어베이스 서버에 저장된 페이퍼 만료 이후 논의된 사항은 다음과 같습니다: 최종 페이퍼를 서버에서 지우기 전 해당 카드를 쓴 사용자의 로컬 데이터에 해당 데이터를 저장시킨다.

파이어베이스 클라우드 함수를 사용하면 (1). 주어진 시간(페이퍼 endTime) 또는 만료 여부에 따라 (2). 해당 페이퍼를 작성하는 데 참여한 모든 사람들에게 다운로드를 받고 로컬 데이터로 저장하라는 (3) 푸시 노티피케이션을 줄 수 있습니다.
하지만 해당 클라우드 함수는 유료 요금제이기 때문에 고려하고 있지 않습니다.

이 문제를 해결할 방법에 관해 생각해봤습니다.

(1). 파이어베이스 노티피케이션을 사용하자 → 클라우드 함수가 아니더라도 클라우드 메시징 기능을 사용하면 파이어베이스 콘솔 상에서 특정 유저에게 페이퍼 ID를 딕셔너리에 포함한 데이터를 푸시 노티피케이션과 함께 줄 수 있습니다. 그런데 이 클라우드 메시징 기능을 보내려면 수동으로 입력해야 하기 때문에(서버가 없기 때문) 번거롭습니다. → 만료 시점에 일일이 페이퍼 아이디에 등록한 사람들을 찾아서 그 사람들의 토큰 아이디에 해당 페이퍼 ID를 실어줘야 합니다

(2). 파이어베이스 노티피케이션을 사용하자 → 클라우드 메시징 함수를 사용할 방법이 한 가지 더 있기는 있습니다. Legacy라고 불리는 REST API를 클라이언트 단에서 직접 사용하는 겁니다. OAuth 토큰을 앱 단에서 HTTP 통신을 통해 호출, 인증받은 뒤에 특정 유저에게 해당 푸쉬 노티피케이션에 사용할 데이터를 함께 전송하는 행위를 클라이언트가 직접 하는 겁니다. 즉 위에서는 파이어베이스 콘솔을 사용하는 개발자가 '직접' 수동으로 해줘야 하는 메시징 입력을 클라이언트 앱에서 해준다는 점만 제외하고는 동일합니다. 

문제점은 다음과 같습니다 → (1). REST API를 사용할 때 쓸 서버 키를 클라이언트가 갖고 있다면 위험성이 크다 (2). "어느 시점"에 최종 페이퍼를 다운받으라고 푸시를 보내는 API를 "누가" 쏠 것인지 결정해야 합니다. 어느 시점은 endTime이라고 합시다. 그렇다면 이때 생기는 문제는 (1). API를 호출할 클라이언트 자체에 이 endTime에 해당 API를 사용하라는 스케줄링이 필요한데 이는 (아마도) 로컬 백그라운드 태스크로 진행될 것이기 때문에 파이어베이스와 별도의 이야기이고 (2). API를 호출할 사람들이 여러 명이기 때문에 불필요한 중복 작업이 생긴다는 점입니다. 2번이야 중복은 넘어간다고 쳐도, 1번에서 생기는 문제점이 걸리는 건 → 로컬 푸시 / 백그라운드 태스크를 사용한다는 점에서 이미 파이어베이스 푸시를 사용할 의미가 퇴색된다는 겁니다

또한 노티피케이션은 사용자에게 허락을 필수적으로 받아야하는 부분이기 때문에 노티 허용이 필수인 시점에서 → 최종 페이퍼 갱신이 이루어지는 건 바람직하지 못하다고 생각합니다.

따라서,
(3). 파이어베이스 노티피케이션 → 클라우드 함수를 사용하지 않는다면 사용할 의미가 없는 것 같습니다.
(4). 로컬 노티피케이션 → (허락했다면) 사용자에게 페이퍼 만료 시간을 알려주고 클릭 시 최종 페이퍼를 자연스럽게 다운로드받을 수 있다는 점에서 매우 좋은 UI를 제공합니다. (허락하지 않았다면) 로컬 노티가 없는 상태에서 최대한 서버에서 만료된 페이퍼를 최종적으로 업데이트할 별도의 로직이 필요합니다

* 노티피케이션을 통해 특정 함수를 실행하게 하는 것 역시 (Foreground, Background, Terminated) 상태를 모두 고려해야 하고 Silent Push Notifications과 같은 별도의 옵션이 많기 때문에 고려할 게 많을 것 같습니다.
* 로컬 푸시와 관계 없이 BGTaskScheduler를 사용하면 앱이 termiated된 상태에서 특정한 작업을 주기적으로 실행할 수 있지만, 확실하게 보장되는 게 아니기 때문에 주의할 요소가 많습니다.
* 로컬 푸시 허용 시 → 앱에 들어오는 여부와 관계없이 특정 시간에 앱을 "깨워서" 특정 작업을 할 수 있습니다. 하지만 이 또한 terminated된 상태에서 어떻게 작동할지는 더 공부해봐야 할 것 같습니다.

* 결론: 

로컬 노티피케이션을 통해서 특정 페이퍼의 만료 시간에 따라 서버에서 최종 페이퍼를 패치, 로컬 데이터에 저장하는 로직을 추가한다.
이 경우 로컬 노티를 클릭할 때 → 자동으로 앱이 켜지기 때문에 (확실하게) 서버에서 페이퍼를 패치 가능합니다. 클릭하지 않는다면 → 로컬 푸시를 보낼 때 앱이 깨기 때문에 클릭 여부와 관계없이 서버에서 데이터를 패치해옵니다

로컬 노티를 사용자가 허락하지 않는다면 → (1). BKTaskScheduler를 사용하자 (2). 앱에 들어올 때까지 기다려서 페이퍼 보관함 뷰에 들어올 때까지 기다린다. 이 경우 확실하게 endTime을 체크, 만료되었다면 서버에서 해당 페이퍼를 패치할 수 있습니다.

일단 이 정도로 만료된 서버 페이퍼 → 로컬 페이퍼로의 다운로드 및 세이브 로직을 생각하고 있습니다.

**Comment by Kelly-Chui** [comment]
>로컬 노티피케이션을 통해서 특정 페이퍼의 만료 시간에 따라 서버에서 최종 페이퍼를 패치, 로컬 데이터에 저장하는 로직을 추가한다.
이 경우 로컬 노티를 클릭할 때 → 자동으로 앱이 켜지기 때문에 (확실하게) 서버에서 페이퍼를 패치 가능합니다. 클릭하지 않는다면 → 로컬 푸시를 보낼 때 앱이 깨기 때문에 클릭 여부와 관계없이 서버에서 데이터를 패치해옵니다

로컬 푸시가 서버에서 데이터를 받아와 저장할 수 있을 정도의 복잡한 로직을 실행 할 수 있을까 걱정이 있었는데, 이런 방식으로 실행 되는군요. 처음에 푸시 알림 권한을 요청할 때, 푸시 알림이 어떻게 이용되는지에 대한 설명을 상세히 해줘야 할 것 같습니다.


혹은
>만료된 페이퍼를 서버에서 지우기 전, 해당 카드를 쓴 사용자의 로컬 데이터에 해당 데이터를 저장시킨다 

이 부분을 다시 한번 논의를 해보는 것도 좋은 방법일것 같네요. 굳이 저장하고 싶지 않은 페이퍼도 있을 수 있는데, 무조건 자동으로 저장하게 만들 필요는 없으니까요.

- Only 수동 저장 (버튼 같은것을 제공해서)
- 페이퍼 생성할때 설정(자동으로 저장 혹은 기간 만료시 삭제 같은 옵션을 제공)

플로우가 그렇게 조잡하지 않고, 나쁘지 않아보여요

**Comment by PJunyeong** [comment]
사실 현재 단계에서는 서버 데이터 삭제를 염두에 두지 않는 게 좋은 것 같긴 하지만, 로컬 노티에 관해서는 확실히 체크해봐야 할 것 같습니다. 언제 페이퍼가 만료되어서 완성본을 볼 수 있을지 설정하기만 한다면 유저에게 굉장히 좋은 UI를 제공할 수 있을 것 같아서요. 그리고 위와 같은 이유로 만일 노티를 추가하는 게 합의가 된다면, 개인적으로는 파이어베이스 함수보다는 로컬 노티 / 함수로 처리하는 게 현 시점에서는 가장 적절한 방법이라고 생각합니다.

**Comment by PJunyeong** [comment]
논의 결과:
(1). 파이어베이스 스토리지를 사용한다.
(2). 서버 상의 최종 페이퍼를 "자동"으로 다운로드받는 것은 페이퍼를 생성하는 (또는 추후 선물받는) 사람으로 한정
(3). 카드 모델의 content가 현재 Data 타입이나, 파이어스토어에 직접적으로 올라가는 게 아니라 파이어베이스 스토리지에 올라간 데이터의 URLString을 가지고 데이터 업/다운로드가 이루어짐
(4). 파이어베이스 푸시 노티피케이션보다는 일단 로컬 노티 사용 쪽으로.
